#BASE IMAGE TAKE FROM : https://github.com/cypress-io/cypress-docker-images
FROM cypress/browsers:node16.16.0-chrome107-ff107-edge
#CREATE THE FOLDER WHERE OUR PROJECT WILL BE STORED
RUN mkdir /my-cy10-project
#WE MAKE IT OUR WORKDIRECTORY
WORKDIR /my-cy10-project
#LETS COPY THE ESSENTIAL FILES THAT WE MUST USE TO RUN OUR SCRIPTS.
COPY ./package.json .
COPY ./cypress.config.js .
COPY ./cypress ./cypress
#INSTALL THE CYPRESS DEPENDENCIES IN THE WORK DIRECTORY
RUN npm i 
#EXECUTE COMMANDS THE CONTAINER WILL USE[EXEC FORM]
ENTRYPOINT ["npx","cypress","run"]
#WITH CMD IN THIS CASE, WE CAN SPECIFY MORE PARAMETERS TO THE LAST ENTRYPOINT.
CMD [""]